language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t fenriss/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true fenriss/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "eu-central-1"
    app: "docker"
    env: "DockerK8sCourseReactFenriss-env"
    bucket_name: "elasticbeanstalk-eu-central-1-370523591161"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY